dpwork_loginpage_Screenshot_folder='dpWorkLoginPageSSFolder'
dpwork_loginpage_documentation_filename='DpWorkLoginPageTestingDocumentation.docx'
dpwork_masterSearch_Screenshot_folder='dpWorkMasterSearchPageSSFolder'
dpwork_masterSearch_documentation_filename='DpWorkMasterSearchTestingDocumentation.docx'
masterSearch_page_evidence_attachment='DpWorkMasterSearchPageTestingDocumentation.docx'
masterSearch_page_report_attachment='DPWorkMasterSearchPageTestReport.html'
masterSearch_testDataFile='masterSearch_testdata.xlsx'
extractGlobalSearchDataFile='globalSearchDataExtract.csv'
extractKeywordSearchDataFile='keywordSearchDataExtract.csv'
extractAreYouUpdatedDataFile='areYouUpdatedDataExtract.csv'
masterSearchGlobalSheetName='GlobalSearch'
masterSearchKeywordSheetName='KeywordSearch'
masterSearchAreYouUpdatedSheetName='AreYouUpdated'
parametersFields='FieldParameters'
fieldValues='All'
attachment1='automation.log'
login_page_evidence_attachment='DpWorkLoginPageTestingDocumentation.docx'
login_page_report_attachment='DPWorkLoginPageTestReport.html'
userRole1='FIELD WORKER'
userRole2='DISTRICT ADMIN'
userRole3='STATE ADMIN'
userRole4='SPECIAL ADMIN'
userRole5='SUPER ADMIN'
config_ini='\\configurations\\config.ini'
projectName='DPWork_2.O_AutomationTesting'
dot_env_file='\\configurations\\.env'

# Global Search data parameters:
GlobalSearchName='GlobalSearchName'

# Keyword Search data parameters:
MemberFirstName='MemberFirstName'
MemberMiddleName='MemberMiddleName'
MemberLastName='MemberLastName'
GuardianFirstName='GuardianFirstName'
GuardianMiddleName='GuardianMiddleName'
GuardianLastName='GuardianLastName'
RitwikFirstName='RitwikFirstName'
RitwikMiddleName='RitwikMiddleName'
RitwikLastName='RitwikLastName'
Address='Address'
InitiationDate='InitiationDate'
PinCode='PinCode'
StateOption='StateOption'
DistrictOption='DistrictOption'

#Are you updated data parameters:
AreYouUpdatedFamilyCode='AreYouUpdatedFamilyCode'