#Login
dpwork_loginpage_Screenshot_folder='dpWorkLoginPageSSFolder'
dpwork_loginpage_documentation_filename='DpWorkLoginPageTestingDocumentation.docx'
Login_testData_File='login_testData.xlsx'
SimpleLoginNewUserOrAllVerified_SheetName='simpleLoginWithAllVerified'
LoginExistingUserPANSEmailNV_SheetName='LoginExistingUserPANSEmailNV'
LoginExistingUserPANSEmailV_SheetName='LoginExistingUserPANSEmailV'
simpleLogin_user_emailAddress='user_emailAddress'
simpleLogin_user_password='user_password'

#Forget Password:
dpwork_forgetPassword_Screenshot_folder='dpWorkForgetPasswordPageSSFolder'
dpwork_forgetPassword_documentation_filename='DpWorkForgetPasswordTestingDocumentation.docx'
forgetPassword_testData_file='forgetPassword_testData.xlsx'
forgetPasswordSheetName1='forgetPasswordSimpleSheet1'
fp_testCaseName='TestCaseName'
fp_emailAddressForPasswordReset='emailAddressForPasswordReset'
fp_newPassword='newPassword'
fp_confirmPassword='confirmPassword'

#Update:
dpwork_updateSerialNumber_Screenshot_folder='dpWorkUpdateSerialNumberPageSSFolder'
dpwork_updateSerialNumber_documentation_filename='DpWorkUpdateSerialNumberTestingDocumentation.docx'
updateSerialNumber_testData_file='updateSerialNumber_testData.xlsx'
updateSerialNumberActiveSheetName1='updateSNActiveSheet1'
updateSerialNumberInActiveSheetName2='updateSNInActiveSheet2'
update_testCaseName='TestCaseName'
update_serialNumber='serialNumber'
update_suggestedMemberName='suggestedMemberName'
update_suggestedGuardianName='suggestedGuardianName'
update_suggestedRitwikName='suggestedRitwikName'
update_dikshayarthiStatus='dikshayarthiStatus'
update_phoneNumber='phoneNumber'
update_familyCode='familyCode'
update_philMemberName='philMemberName'
update_emailAddress='emailAddress'
update_permanentAddress='permanentAddress'
update_permanentLandmark='permanentLandmark'
update_permanentPincode='permanentPincode'
update_permanentPostoffice='permanentPostoffice'
update_presentAddress='presentAddress'
update_presentLandmark='presentLandmark'
update_presentPincode='presentPincode'
update_presentPostoffice='presentPostoffice'
update_comments='comments'



dpwork_masterSearch_Screenshot_folder='dpWorkMasterSearchPageSSFolder'
dpwork_masterSearch_documentation_filename='DpWorkMasterSearchTestingDocumentation.docx'
masterSearch_page_evidence_attachment='DpWorkMasterSearchPageTestingDocumentation.docx'
masterSearch_page_report_attachment='DPWorkMasterSearchPageTestReport.html'
masterSearch_testDataFile='masterSearch_testdata.xlsx'
extractGlobalSearchDataFile='globalSearchDataExtract.csv'
extractKeywordSearchDataFile='keywordSearchDataExtract.csv'
extractAreYouUpdatedDataFile='areYouUpdatedDataExtract.csv'
masterSearchGlobalSheetName='GlobalSearch'
masterSearchKeywordSheetName='KeywordSearch'
masterSearchAreYouUpdatedSheetName='AreYouUpdated'
parametersFields='FieldParameters'
fieldValues='All'
attachment1='automation.log'
login_page_evidence_attachment='DpWorkLoginPageTestingDocumentation.docx'
login_page_report_attachment='DPWorkLoginPageTestReport.html'
userRole1='FIELD WORKER'
userRole2='DISTRICT ADMIN'
userRole3='STATE ADMIN'
userRole4='SPECIAL ADMIN'
userRole5='SUPER ADMIN'
config_ini='\\configurations\\config.ini'
projectName='DPWork_2.O_AutomationTesting'
dot_env_file='\\configurations\\.env'

# Global Search data parameters:
GlobalSearchName='GlobalSearchName'

# Keyword Search data parameters:
MemberFirstName='MemberFirstName'
MemberMiddleName='MemberMiddleName'
MemberLastName='MemberLastName'
GuardianFirstName='GuardianFirstName'
GuardianMiddleName='GuardianMiddleName'
GuardianLastName='GuardianLastName'
RitwikFirstName='RitwikFirstName'
RitwikMiddleName='RitwikMiddleName'
RitwikLastName='RitwikLastName'
Address='Address'
InitiationDate='InitiationDate'
PinCode='PinCode'
StateOption='StateOption'
DistrictOption='DistrictOption'

#Are you updated data parameters:
AreYouUpdatedFamilyCode='AreYouUpdatedFamilyCode'

#DPNF (Add and Edit)
dpwork_addToDpnf_Screenshot_folder='dpWorkAddToDpnfSSFolder'
dpwork_addToDpnf_documentation_filename='DpWorkAddToDpnfTestingDocumentation.docx'
dpnf_testDataFile='dpnf_testData.xlsx'
addToDpnf_htmlReportFile='DPWorkAddToDpnfTestReport.html'
dpwork_editDpnf_Screenshot_folder='dpWorkEditDpnfSSFolder'
dpwork_editDpnf_documentation_filename='DpWorkEditDpnfTestingDocumentation.docx'
editDpnf_htmlReportFile='DPWorkEditDpnfTestReport.html'
addToDpnfSheetName='addToDpnf'
editDpnfSheetName='editDpnf'

#Add To DPNF and Edit DPNF
MemberFirstName_Dpnf='MemberFirstName'
MemberMiddleName_Dpnf='MemberMiddleName'
MemberLastName_Dpnf='MemberLastName'
GuardianFirstName_Dpnf='GuardianFirstName'
GuardianMiddleName_Dpnf='GuardianMiddleName'
GuardianLastName_Dpnf='GuardianLastName'
HusbandFirstName_Dpnf='HusbandFirstName'
HusbandMiddleName_Dpnf='HusbandMiddleName'
HusbandLastName_Dpnf='HusbandLastName'
FamilyCode_Dpnf='FamilyCode'
PhilMemberName_Dpnf='PhilMemberName'
ContactNumber_Dpnf='ContactNumber'
GenderType_Dpnf='GenderType'
MaritalStatus_Dpnf='MaritalStatus'
DikshaAddress_Dpnf='DikshaAddress'
DikshaLandmark_Dpnf='DikshaLandmark'
DikshaPincode_Dpnf='DikshaPincode'
PresentAddress_Dpnf='PresentAddress'
PresentLandmark_Dpnf='PresentLandmark'
PresentPincode_Dpnf='PresentPincode'
PresentPostOffice_Dpnf='PresentPostOffice'
PermanentAddress_Dpnf='PermanentAddress'
PermanentLandmark_Dpnf='PermanentLandmark'
PermanentPincode_Dpnf='PermanentPincode'
PermanentPostOffice_Dpnf='PermanentPostOffice'
checkboxStatus_Dpnf='checkboxStatus'
birthYear_Dpnf='birthYear'
birthMonth_Dpnf='birthMonth'
birthDate_Dpnf='birthDate'
dikshaYear_Dpnf='dikshaYear'
dikshaMonth_Dpnf='dikshaMonth'
dikhaDay_Dpnf='dikhaDay'
comment_Dpnf='comment'
alreadyDpnfed_dpnf='AlreadyDpnfed'
TestCaseName_Dpnf='TestCaseName'
memberAlreadyUpdatedStatus_dpnf='memberAlreadyUpdatedStatus'

#first time signup and login in Dp Portal:
dpwork_firstTimeSignUpLogin_Screenshot_folder1='dpWorkNewUserSignUpSSOTPResendFolder'
dpwork_firstTimeSignUpLogin_Screenshot_folder2='dpWorkNewUserSignUpSSOTPOnceFolder'
dpwork_firstTimeSignUpLogin_documentation_filename='DpWorkNewUserSignUpTestingDocumentation.docx'
firstTimeSignUpLogin_testDataFile='newUserSignUp_testData.xlsx'
newUserSignUpLoginSheetName1='newUserSignUpAndLoginOTPResend'
newUserSignUpLoginSheetName2='newUserSignUpAndLoginOTPOnce'
newSignUp_testCaseName='TestCaseName'
newSignUp_FirstName='FirstName'
newSignUp_LastName='LastName'
newSignUp_ContactNumber='ContactNumber'
newSignUp_EmailAddress='EmailAddress'
newSignUp_Password='Password'
newSignUp_ConfirmPassword='ConfirmPassword'
newSignUp_Address='Address'
newSignUp_Pincode='Pincode'
newSignUp_FamilyCode='FamilyCode'
newSignUp_PhilName='PhilName'
newSignUp_report_attachment1='DPWorkNewSignUpTestReport.html'