dpwork_loginpage_Screenshot_folder='dpWorkLoginPageSSFolder'
dpwork_loginpage_documentation_filename='DpWorkLoginPageTestingDocumentation.docx'
dpwork_masterSearch_Screenshot_folder='dpWorkMasterSearchPageSSFolder'
dpwork_masterSearch_documentation_filename='DpWorkMasterSearchTestingDocumentation.docx'
masterSearch_page_evidence_attachment='DpWorkMasterSearchPageTestingDocumentation.docx'
masterSearch_page_report_attachment='DPWorkMasterSearchPageTestReport.html'
masterSearch_testDataFile='masterSearch_testdata.xlsx'
extractGlobalSearchDataFile='globalSearchDataExtract.csv'
extractKeywordSearchDataFile='keywordSearchDataExtract.csv'
extractAreYouUpdatedDataFile='areYouUpdatedDataExtract.csv'
masterSearchGlobalSheetName='GlobalSearch'
masterSearchKeywordSheetName='KeywordSearch'
masterSearchAreYouUpdatedSheetName='AreYouUpdated'
parametersFields='FieldParameters'
fieldValues='All'
attachment1='automation.log'
login_page_evidence_attachment='DpWorkLoginPageTestingDocumentation.docx'
login_page_report_attachment='DPWorkLoginPageTestReport.html'
userRole1='FIELD WORKER'
userRole2='DISTRICT ADMIN'
userRole3='STATE ADMIN'
userRole4='SPECIAL ADMIN'
userRole5='SUPER ADMIN'
config_ini='\\configurations\\config.ini'
projectName='DPWork_2.O_AutomationTesting'
dot_env_file='\\configurations\\.env'

# Global Search data parameters:
GlobalSearchName='GlobalSearchName'

# Keyword Search data parameters:
MemberFirstName='MemberFirstName'
MemberMiddleName='MemberMiddleName'
MemberLastName='MemberLastName'
GuardianFirstName='GuardianFirstName'
GuardianMiddleName='GuardianMiddleName'
GuardianLastName='GuardianLastName'
RitwikFirstName='RitwikFirstName'
RitwikMiddleName='RitwikMiddleName'
RitwikLastName='RitwikLastName'
Address='Address'
InitiationDate='InitiationDate'
PinCode='PinCode'
StateOption='StateOption'
DistrictOption='DistrictOption'

#Are you updated data parameters:
AreYouUpdatedFamilyCode='AreYouUpdatedFamilyCode'

#DPNF (Add and Edit)
dpwork_addToDpnf_Screenshot_folder='dpWorkAddToDpnfSSFolder'
dpwork_addToDpnf_documentation_filename='DpWorkAddToDpnfTestingDocumentation.docx'
dpnf_testDataFile='dpnf_testData.xlsx'
addToDpnf_htmlReportFile='DPWorkAddToDpnfTestReport.html'
dpwork_editDpnf_Screenshot_folder='dpWorkEditDpnfSSFolder'
dpwork_editDpnf_documentation_filename='DpWorkEditDpnfTestingDocumentation.docx'
editDpnf_htmlReportFile='DPWorkEditDpnfTestReport.html'
addToDpnfSheetName='addToDpnf'
editDpnfSheetName='editDpnf'

#Add To DPNF and Edit DPNF
MemberFirstName_Dpnf='MemberFirstName'
MemberMiddleName_Dpnf='MemberMiddleName'
MemberLastName_Dpnf='MemberLastName'
GuardianFirstName_Dpnf='GuardianFirstName'
GuardianMiddleName_Dpnf='GuardianMiddleName'
GuardianLastName_Dpnf='GuardianLastName'
HusbandFirstName_Dpnf='HusbandFirstName'
HusbandMiddleName_Dpnf='HusbandMiddleName'
HusbandLastName_Dpnf='HusbandLastName'
FamilyCode_Dpnf='FamilyCode'
PhilMemberName_Dpnf='PhilMemberName'
ContactNumber_Dpnf='ContactNumber'
GenderType_Dpnf='GenderType'
MaritalStatus_Dpnf='MaritalStatus'
DikshaAddress_Dpnf='DikshaAddress'
DikshaLandmark_Dpnf='DikshaLandmark'
DikshaPincode_Dpnf='DikshaPincode'
PresentAddress_Dpnf='PresentAddress'
PresentLandmark_Dpnf='PresentLandmark'
PresentPincode_Dpnf='PresentPincode'
PresentPostOffice_Dpnf='PresentPostOffice'
PermanentAddress_Dpnf='PermanentAddress'
PermanentLandmark_Dpnf='PermanentLandmark'
PermanentPincode_Dpnf='PermanentPincode'
PermanentPostOffice_Dpnf='PermanentPostOffice'
checkboxStatus_Dpnf='checkboxStatus'
birthYear_Dpnf='birthYear'
birthMonth_Dpnf='birthMonth'
birthDate_Dpnf='birthDate'
dikshaYear_Dpnf='dikshaYear'
dikshaMonth_Dpnf='dikshaMonth'
dikhaDay_Dpnf='dikhaDay'
comment_Dpnf='comment'
alreadyDpnfed_dpnf='AlreadyDpnfed'
TestCaseName_Dpnf='TestCaseName'
memberAlreadyUpdatedStatus_dpnf='memberAlreadyUpdatedStatus'

